services:
  app:
    container_name: python-app
    image: python-mysql:v0.1
    build: .
    ports:
      - ${SERVER_PORT}:5000
    environment:
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  db:
    container_name: mysql
    image: mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  sv_mysql_data:
